//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int MaThanhToan { get; set; }
        public string maDH { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public double TongTien { get; set; }
        public bool TrangThaiThanhToan { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
